services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
      - ./api/vendor:/var/www/vendor
      - ./api/storage:/var/www/storage
    networks:
      - app-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:LOXelluMKsSsRbHUBda4GBJn5AqlfOxpggJedO4K4oc=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=travel_manager
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_manager
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"

  frontend:
    build:
      context: ./travel-manager
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./travel-manager:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - NODE_ENV=development

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: