services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./storage:/var/www/storage
    ports:
      - "9000:9000"
    networks:
      - laravel
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:LOXelluMKsSsRbHUBda4GBJn5AqlfOxpggJedO4K4oc=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=travel_manager
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_manager
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3507:3306"

  # nginx:
  #   image: nginx:alpine
  #   container_name: laravel_nginx
  #   restart: unless-stopped
  #   ports:
  #     - "9000:80"
  #   volumes:
  #     - .:/var/www
  #     - ./nginx:/etc/nginx/conf.d
  #   networks:
  #     - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:


